#Laravel Setup, PHP Code Quality Detectors and PHP Unit Tests
name: CI Jobs

on: [ push, pull_request ]

jobs:

  job:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [
          #          7.0.*,
          #          7.1.*,
          #          7.3.*,
          7.4.*
        ]
        laravel: [
          #          6.*,
          7.*
        ]
        dependency-version: [prefer-stable]

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }} (${{ matrix.dependency-version }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: PHP Version
        run: php --version

      - name: Lint
        run: find -L "src/" -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l

      - name: Copy/Paste Detector
        run: php vendor/bin/phpcpd src/

      - name: Mess Detector
        run: find -L "src/" -name '*.php' -print0 | xargs -0 -n 1 -P 4 -I{} php vendor/bin/phpmd {} text phpmd.xml

      - name: Code Sniffer
        run: |
          php vendor/bin/phpcbf src/
          php vendor/bin/phpcs src/

      - name: PHPUnit
        run: vendor/bin/phpunit  --no-coverage --debug
